export const SET_ACTIVE_PIN = 'SET_ACTIVE_PIN';
export const SET_HIGHLIGHT_FIELD = 'SET_HIGHLIGHT_FIELD';
export const UNSET_HIGHLIGHT_FIELD = 'UNSET_HIGHLIGHT_FIELD';
export const TRY_MOVE_PIN = 'TRY_MOVE_PIN';
